language: php
php:
  - 7.1
  - 7.2
  - master


env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS website_db;" -uroot; fi
  - mysql -e "USE mysql;"
  - mysql - e "DROP TABLE IF EXISTS users;"
  - mysql - e "CREATE TABLE users (
        user_id INT(32) NOT NULL AUTO_INCREMENT,
        user_name VARCHAR(50) NOT NULL,
        user_pass VARCHAR(255) NOT NULL, -- NOTE: Never store raw password. Must be one way crypto hashed first.
        user_email VARCHAR(255) NOT NULL,
        user_date DATETIME NOT NULL,
        user_birthDate DATE NOT NULL,
        user_gender CHAR(1) NOT NULL,
        user_level INT(16),
        user_karma_score INT(32) DEFAULT 0, -- Reddit-like point system
        user_type INT(3), 
        user_answers_count INT(16), -- keep track of the user's contribution
        user_questions_count INT (16),
        user_profile_description_short VARCHAR(300),
        user_profile_description_long VARCHAR(2000),
        user_email_notification_on INT (1) DEFAULT 1, -- If 1: notifications will also be forwarded via email to user
        user_deleted INT(1) DEFAULT 0, -- If 0: user is active. If 1, user has deleted his account
        UNIQUE INDEX user_name_unique (user_name),
        PRIMARY KEY (user_id)
        );"
        
  


script:
  - vendor/bin/phpunit

before_install:
  - composer update
  - mysql -e 'CREATE DATABASE website_db;'
