language: php
php:
  - 7.1
  - 7.2
  - master

services:
  - mysql

#before script:
#- mysql -e 'CREATE DATABASE website_db;'

script:
  - vendor/bin/phpunit

before_install:
  - composer update
  - mysql -u root --password="" < ./config/travisDB.sql