language: php
php:
  - 7.1
  - 7.2
  - master


env:
  - DB=mysql
  
services:
  - mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS website_db;" -uroot; fi
  - mysql - e "CREATE TABLE IF NOT EXISTS website_db.questions (question_id INT(16) NOT NULL AUTO_INCREMENT, question_title VARCHAR(255), question_date DATETIME, question_cat INT(16), question_by_user VARCHAR(50), question_upvote INT(16) DEFAULT 0, question_keyword_tag VARCHAR(500), question_description VARCHAR(1000), question_view_count INT(16) DEFAULT 0, question_deleted INT(1) DEFAULT 0, PRIMARY KEY (question_id));"
  - mysql - e "CREATE TABLE IF NOT EXISTS website_db.answers(answers_id INT(16) NOT NULL AUTO_INCREMENT,answers_content VARCHAR(5000),answers_date DATETIME,reply_questions INT(16) NOT NULL,reply_by INT(32),answers_by_user VARCHAR(50),answers_upvotes INT(8),answers_downvotes INT(8),answer_state INT(1) DEFAULT 1,answer_deleted INT(1) DEFAULT 0,PRIMARY KEY (answers_id));"
  - mysql - e "CREATE TABLE IF NOT EXISTS website_db.tags (tag_id INT(16) NOT NULL AUTO_INCREMENT, tag_name VARCHAR(255) NOT NULL, tag_description VARCHAR(255),   UNIQUE INDEX tag_name_unique (tag_name), PRIMARY KEY (tag_id));"
  - mysql - e "CREATE TABLE IF NOT EXISTS website_db.question_tags (question_id INT(16) NOT NULL,  tag_id INT(16) NOT NULL, PRIMARY KEY (question_id, tag_id));"

  
script:
  - vendor/bin/phpunit

before_install:
  - composer update
  - mysql -e 'CREATE DATABASE website_db;'
