language: php
php:
  - 7.1
  - 7.2
  - master


env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS website_db;" -uroot; fi
  - sh -c 'mysql -e DROP TABLE IF EXISTS questions;'
  - sh -c 'mysql - e CREATE TABLE questions (
question_id INT(16) NOT NULL AUTO_INCREMENT,
question_title VARCHAR(255),
question_date DATETIME,
question_cat INT(16), -- foreign key to cat_id in table categories
question_by INT(32),-- foreign key to users_id
question_by_user VARCHAR(50), -- Minimize processing time/reducing inner join calls
question_upvote INT(16) DEFAULT 0,
question_keyword_tag VARCHAR(500), -- we can add tags to the question later
question_description VARCHAR(1000),
question_view_count INT(16) DEFAULT 0,
question_deleted INT(1) DEFAULT 0, -- If 0: question is up. If 1, user has deleted the question
PRIMARY KEY (question_id)
) ENGINE=INNODB;'


script:
  - vendor/bin/phpunit

before_install:
  - composer update
  - mysql -e 'CREATE DATABASE website_db;'
